properties:
  permissions: false
  update-delay: 60
  time-after-draws: 5
  reminder-message: '&eDont forget to check your servers lotteries. Type /lottery
    list to list lotteries.'
  reminder-message-time: 30
  sign-message: '&eName: <name><newline>&eTicket Cost: <ticketcost>'
signs:
  normal:
    line1: <name>
    line2: <time>
    line3: <reward>
  drawing:
    line1: <name>
    line2: Drawing...
    line3: <reward>
  over:
    line1: <name>
    line2: Over
    line3: <winner>
