# config properties
# NOTE: color codes can be used in messages
#
properties:

    # reminder message to send out
    reminder-message: '&e[Lottery+] - Dont forget to check your servers lotteries. Type /lottery list to list lotteries.'

    # sign message to send when users use signs
    #
    # <name> - name of the lottery
    # <ticketcost> - cost of a ticket for the lottery
    # <reward> - reward of the lottery
    # <time> - time until drawing
    # <winner> - most recent winner of the lottery
    # <ticket_tax> - ticket tax of the lottery
    # <pot_tax> - pot tax of the lottery
    #
    sign-message: '&eName: <name><newline>&eTicket Cost: <ticketcost>'
    
    # message to send to players about the main lotteries
    #
    # <name> - name of the lottery
    # <ticketcost> - cost of a ticket for the lottery
    # <reward> - reward of the lottery
    # <time> - time until drawing
    # <winner> - most recent winner of the lottery
    # <ticket_tax> - ticket tax of the lottery
    # <pot_tax> - pot tax of the lottery
    #
    main-lotteries-message: '&e[Lottery+] - <name>: Time Left: <time>, Reward: <reward>'

    # buy message to send out when a player buys a ticket
    #
    # <player> - player who bought the tickets
    # <tickets> - amount of tickets the player bought
    # <lottery> - the lottery the player bought it from
    #
    buy-message: '&e<player> has bought <tickets> tickets for <lottery>'
    
    # message to be printed out when a lottery
    # reaches its defined 'warning times'
    # see defaults -> warning-times: for warning time
    warning-message: '&e[Lottery+] - There are <time> left until the drawing occurs for <name>.'

    # whether to broadcast out the buy message or not
    buy-enable: true

    # delay betwween lottery savings, x minutes: set to 0 or less to disable, can also use '/lottery save' to force save lotteries
    save-delay: 15

    # delay between update checks, x minutes: set to 0 or less to disable, can also use '/lottery update' to check on updates
    update-delay: 30
    
    # the delay that takes place between a lottery drawing and when it announces the winner, x seconds
    draw-delay: 3

    # delay between reminder messages, x minutes: set to 0 or less to disable
    reminder-message-delay: 10

    # whether item rewards should drop on the ground near players or should it go in their inventory
    should-drop: true
    
    # whether to log lottery savings or not
    should-log: false
    
    # whether players should be allowed to buy tickets during the lottery drawing
    buy-during-draw: false

    # the line separator used in messages
    line-separator: '<newline>'

    # the format used for money, must contain '<money>' in format
    money-format: '$<money>'
    
    # sign tag used for lottery signs, can have color codes
    sign-tag: '&a[Lottery+]'
    
    # prefix used in chat, can have color codes
    chat-prefix: '&e[LotteryPlus] - '

    # the lotteries that the user will be notified about when a player joins the server
    # ex: 'MAIN1 MAIN2 MAIN3', ect...
    main-lotteries: ''
    



# lottery defaults, these can be defined in any lottery,
# though you can alter these where they affect every lottery
defaults:

    # time between drawings, x hours
    time: 48

    # max tickets a player can buy, set to negative for infinite limit
    max-tickets: -1

    # min players needed in order to draw the lottery
    min-players: 2

    # max players that is allows in the lottery, set to negative for infinite limit
    max-players: 10

    # time taken from the lottery when a player buys the ticket, x seconds
    cooldown: 0

    # seed used for the random generator
    seed: 'LotteryPlus'

    # item rewards that are added to the lottery
    # defined examples: '35:3*64' - stack of light blue wool
    # format -> 'materialID:meta_data*amount'
    # more examples: '351:0*1 351:1*1 351:2*1'
    item-rewards: ''

    # whether this lottery has item rewards only or not
    item-only: false

    # whether this lottery should repeat after the next drawing
    repeat: true
    
    # whether the pot should be cleared if a winner is not drawn
    clear-pot: false
    
    # whether the rewards should be cleared if a winner is not drawn
    clear-rewards: false
    
    # how many tickets are available for a lottery, set to 0 for infinite tickets
    ticket-limit: 0

    # the starting pot
    pot: 1000.00

    # cost of lottery tickets
    ticket-cost: 10.00
    
    # whether to use vault
    use-vault: false
    
    # id for material used when 'use-vault' is false
    material-id: 266
    
    # alias for the currency when 'use-vault' is false
    material-name: Gold Ingot

    # ticket tax used
    # ex: 
    # ticket-tax: 10.00
    # ticket-cost: 50.00
    #
    # 10 tickets -> player pays 500.00, but 450.00 of it goes to the pot
    #
    ticket-tax: 0.0

    # ticket tax used
    # ex: 
    # pot-tax: 10.00
    # pot: 1000.00
    #
    # only 900.00 is awarded to the player 
    #
    pot-tax: 0.0
    
    # used to alert players about the current time of the lottery
    # how to:
    # 
    # '24h 12h 6h 3h 1h'
    # this will alert the players at 24, 12, 6, 3, and 1 hours
    # 
    # <amount><symbol>
    # symbols:
    # w: weeks
    # d: days
    # h: hours
    # m: minutes
    # s: seconds
    #
    #see: properties -> warning-message: for control on what the message is printed
    warning-times: ''

    # amount added to ticket-cost after failed drawing
    reset-add-ticket-cost: 0.00

    # amount added to pot after failed drawing
    reset-add-pot: 0.00

    # amount added to ticket-tax after failed drawing
    reset-add-ticket-tax: 0.00

    # amount added to pot-tax after failed drawing
    reset-add-pot-tax: 0.00

    # amount added to max-tickets after failed drawing
    reset-add-max-tickets: 0

    # amount added to min-players after failed drawing
    reset-add-min-players: 0

    # amount added to max-players after failed drawing
    reset-add-max-players: 0

    # amount added to cooldown after failed drawing
    reset-add-cooldown: 0

    # amount added to time after failed drawing
    reset-add-time: 0
    
    # items add after failed drawing, defined the same way as 'item-rewards'
    reset-add-item-rewards: ''