properties:
  reminder-message: '&eDont forget to check your servers lotteries. Type /lottery list to list lotteries.'
  permissions: false
  reminder-message-time: 30
  sign-message: '&eName: <name><newline>&eTicket Cost: <ticketcost>'
lottery properties:
  min-players: 2
  default-ticketcost: 1.0
  max-players: 10
  default-pot: 100.0
signs:
  normal:
    line1: '<name>'
    line2: '<time>'
    line3: '<reward>'
  drawing:
    line1: '<name>'
    line2: 'Drawing...'
    line3: '<reward>'
  over:
    line1: '<name>'
    line2: 'Over'
    line3: '<winner>'
