name: LotteryPlus
main: com.randude14.lotteryplus.Plugin
author: Randude14
description: 'Powerful and funtional lottery interface that makes lotteries easy to make and fun to play!'
website: 'http://dev.bukkit.org/server-mods/lotteryplus/'
version: 0.7.8
commands: 
    lottery: 
        description: get available commands
        aliases: '[l, lp, lot]'